### ISSUE TITLE
test runner: catch UnicodeDecodedError on harness call

### ISSUE THREAD

**Issue by jsarzy** [phoenix-rtos/phoenix-rtos-project#175]
A failing test can produce an unpredictable output like bytes that can't be decode in `utf-8`. Now the runner will throw an exception without any information what have been read before failure. We should try to take info from pyexpect buffers and keep backtrace of the exception (now `assert` is handled this way).

An example exception:
```
armv7m7-imxrt106x: phoenix-rtos-tests.sample.test.unity: FAILED
	EXCEPTION:
	Traceback (most recent call last):
	  File "/actions-runner/_work/phoenix-rtos-project/phoenix-rtos-project/phoenix-rtos-tests/trunner/testcase.py", line 167, in handle
	    res = self.harness(proc)
	  File "/actions-runner/_work/phoenix-rtos-project/phoenix-rtos-project/phoenix-rtos-tests/trunner/harness.py", line 51, in harness
	    idx = proc.expect([
	  File "/opt/venv/lib/python3.8/site-packages/pexpect/spawnbase.py", line 343, in expect
	    return self.expect_list(compiled_pattern_list,
	  File "/opt/venv/lib/python3.8/site-packages/pexpect/spawnbase.py", line 372, in expect_list
	    return exp.expect_loop(timeout)
	  File "/opt/venv/lib/python3.8/site-packages/pexpect/expect.py", line 169, in expect_loop
	    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
	  File "/opt/venv/lib/python3.8/site-packages/pexpect/fdpexpect.py", line 148, in read_nonblocking
	    return super(fdspawn, self).read_nonblocking(size)
	  File "/opt/venv/lib/python3.8/site-packages/pexpect/spawnbase.py", line 181, in read_nonblocking
	    s = self._decoder.decode(s, final=False)
	  File "/usr/lib/python3.8/codecs.py", line 322, in decode
	    (result, consumed) = self._buffer_decode(data, self.errors, final)
	UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by damianloew** [comment]
Resolved
